import os
import frontmatter  # Ensure 'python-frontmatter' is installed
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# Assuming deepseek_client.py defines a client similar to OpenAI's API
from translation.deepseek_client import call_deepseek_api  # Adjust import if necessary based on your deepseek_client.py

def generate_recommendations():
    # Path to the posts directory
    posts_dir = '_posts/en'

    # List all .md files in the posts directory
    post_files = [f for f in os.listdir(posts_dir) if f.endswith('.md')]
    print(f"Found {len(post_files)} post files in {posts_dir}")

    # Parse each markdown file to extract the title
    all_titles = []
    for file in post_files:
        # Load the markdown file content and front matter
        file_path = os.path.join(posts_dir, file)
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                post = frontmatter.load(f)
                title = post.get('title', file.replace('.md', ''))  # Default to filename if no title is found
            print(f"  Extracted title: {title} from {file}")
            all_titles.append(title)
        except Exception as e:
            print(f"Error processing {file}: {e}")

    # Sort titles alphabetically or by some order if needed; here just as list
    all_titles.sort()

    # Prepare the prompt for the AI
    prompt = f"""Here is a list of my blog post titles:
{'\n'.join(all_titles)}

Recommend the ones that would be most interesting to a visitor who is a 10-year experienced backend engineer. Focus on technical, programming, or engineering-related topics that align with backend development interests like proxies, AI tools, or similar. Provide a list of recommended titles, each with a brief reason why it's suitable. Format the output as markdown, with recommended titles as bullet points, e.g.:
- Title: Reason.
"""

    ai_response = call_deepseek_api(prompt=prompt)

    # Generate the markdown content
    content = f"""---
audio: false
generated: true
lang: en
layout: post
title: Recommended Blog Posts for Experienced Backend Engineers
translated: false
---

These recommendations are generated by AI based on the current blog posts, tailored for a 10-year backend engineer. Update this file by running the script every half year to refresh based on new posts.

{ai_response}
"""

    # Update the markdown file
    file_path = os.path.join('original', '2025-07-22-recommend-for-engineers-en.md')
    try:
        with open(file_path, 'w', encoding='utf-8') as md_file:
            md_file.write(content)
        print(f"Updated {file_path}")
    except Exception as e:
        print(f"Error updating {file_path}: {e}")

if __name__ == "__main__":
    generate_recommendations()