import os
import frontmatter  # Ensure 'python-frontmatter' is installed
import sys
from datetime import datetime, timedelta

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# Assuming deepseek_client.py defines a client similar to OpenAI's API
from translation.deepseek_client import call_deepseek_api  # Adjust import if necessary based on your deepseek_client.py

def generate_recommendations():
    # Path to the posts directory
    posts_dir = '_posts/en'

    # List all .md files in the posts directory
    post_files = [f for f in os.listdir(posts_dir) if f.endswith('.md')]
    print(f"Found {len(post_files)} post files in {posts_dir}")

    # Filter posts from the last year based on the date in the filename
    one_year_ago = datetime.now() - timedelta(days=365)
    recent_post_files = []
    for file in post_files:
        try:
            # Extract date from filename (assuming format YYYY-MM-DD-title.md)
            date_str = file.split('-', 3)[:3]
            if len(date_str) == 3:
                file_date = datetime.strptime('-'.join(date_str), '%Y-%m-%d')
                if file_date >= one_year_ago:
                    recent_post_files.append(file)
        except (ValueError, IndexError):
            print(f"Could not parse date from {file}, skipping")

    print(f"Found {len(recent_post_files)} posts from the last year")

    # Parse each markdown file to extract the title and filename
    post_data = []
    for file in recent_post_files:
        # Load the markdown file content and front matter
        file_path = os.path.join(posts_dir, file)
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                post = frontmatter.load(f)
                title = post.get('title', file.replace('.md', ''))  # Default to filename if no title is found
            print(f"  Extracted title: {title} from {file}")
            # Extract the base name for the link (e.g., 'car-lamp-en' from '2025-07-21-car-lamp-en.md')
            base_name = file.split('-', 3)[-1].replace('.md', '')
            post_data.append({'title': title, 'link': base_name})
        except Exception as e:
            print(f"Error processing {file}: {e}")

    # Sort titles alphabetically or by some order if needed
    post_data.sort(key=lambda x: x['title'])

    # Prepare a list of titles with links for the prompt
    all_posts_with_links = [f"- [{item['title']}](./{item['link']})" for item in post_data]

    # Prepare the prompt for the AI
    prompt = f"""Here is a list of my blog post titles with their links from the last year:
{'\n'.join(all_posts_with_links)}

Recommend the ones that would be most interesting to a visitor who is a 10-year experienced backend engineer. Focus on technical, programming, or engineering-related topics that align with backend development interests like proxies, AI tools, or similar. Provide a list of recommended titles, each with a brief reason why it's suitable. Format the output as markdown, with recommended titles as bullet points. Include a link to each post in the format [title](./link), where 'link' is the base name of the file. For example, for a post titled 'Car Lamp' with a file name like '2025-07-21-car-lamp-en.md', the link should be './car-lamp-en'. Use the following format for each recommendation:
- [Title](./link): Reason.
"""

    ai_response = call_deepseek_api(prompt=prompt)

    # Generate the markdown content
    content = f"""---
audio: false
generated: true
lang: en
layout: post
title: Recommended Blog Posts for Experienced Backend Engineers
translated: false
---

These recommendations are generated by AI based on blog posts from the last year, tailored for a 10-year backend engineer. Update this file by running the script every half year to refresh based on new posts.

{ai_response}
"""

    # Update the markdown file
    file_path = os.path.join('original', '2025-07-22-recommend-for-engineers-en.md')
    try:
        with open(file_path, 'w', encoding='utf-8') as md_file:
            md_file.write(content)
        print(f"Updated {file_path}")
    except Exception as e:
        print(f"Error updating {file_path}: {e}")

if __name__ == "__main__":
    generate_recommendations()