import os
from datetime import datetime
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from translation.deepseek_client import call_deepseek_api

def determine_output_filename(output_file, recommend_desc):
    """Determine the output filename, generating a default if none provided."""
    if output_file is None:
        today = datetime.now().strftime('%Y-%m-%d')
        default_name_prompt = f"""Generate a short, unique filename segment for a blog post recommending content for a {recommend_desc}. The format should be something like 'recommend-for-engineers'. Only output one without quotes. Keep it concise and relevant."""
        default_name_response = call_deepseek_api(prompt=default_name_prompt).strip()
        output_file = os.path.join('original', f"{today}-{default_name_response}-en.md")
    else:
        output_file = os.path.join('original', output_file)
    return output_file

def write_recommendations_file(output_file, ai_response, years, recommend_desc):
    """Write the AI-generated recommendations to a markdown file."""
    content = f"""---
audio: false
generated: true
lang: en
layout: post
title: Recommended Blog Posts for {recommend_desc.capitalize()}
translated: false
---

These recommendations are generated by AI based on blog posts from the last {years} year(s), tailored for a {recommend_desc}. Update this file by running the script every half year to refresh based on new posts.

{ai_response}
"""
    try:
        with open(output_file, 'w', encoding='utf-8') as md_file:
            md_file.write(content)
        print(f"Updated {output_file}")
    except Exception as e:
        print(f"Error updating {output_file}: {e}")
        
if __name__ == "__main__":
    output_file = determine_output_filename(None, "software engineers")
    write_recommendations_file(output_file, "Sample AI response content", 2, "software engineers")