name: Update NYTimes Articles

on:
  schedule:
    - cron: '40 23 * * *'
  workflow_dispatch:

jobs:
  update_nytimes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Set up Python 3.10.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run NYTimes Script
        id: nytimes_update
        run: |
          OUTPUT=$(python scripts/nytimes/nytimes.py)
          if [[ "$OUTPUT" == *"The Markdown file was updated with new links."* ]]; then
            echo "nytimes_updated=true" >> "$GITHUB_OUTPUT"
          else
            echo "nytimes_updated=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit NYTimes Changes
        if: steps.nytimes_update.outputs.nytimes_updated == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add original/2025-03-14-nytimes-en.md
          git diff --cached --quiet || git commit -m "chore(nytimes): Update NYTimes links"
          git push || {
            echo "Push failed, attempting pull and merge"
            git pull --rebase
            git push
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Release Hash
        if: steps.nytimes_update.outputs.nytimes_updated == 'true'
        run: python scripts/release/update_release.py

      - name: Setup Pages
        if: steps.nytimes_update.outputs.nytimes_updated == 'true'
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        if: steps.nytimes_update.outputs.nytimes_updated == 'true'
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload Artifact
        if: steps.nytimes_update.outputs.nytimes_updated == 'true'
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        if: steps.nytimes_update.outputs.nytimes_updated == 'true'
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Send Telegram Message
        if: steps.nytimes_update.outputs.nytimes_updated == 'true'
        run: |
          python scripts/release/telegram_bot.py --job send_message
        env:
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}